### ISSUE TITLE
Modernize test suite

### ISSUE THREAD

**Issue by deeplook** [deeplook/svglib#1]
- move `src/test` directory one level up and rename to `tests`
- convert `unittest` to `pytest` (done)
- add `tox.ini` and/or `pytest.ini`

**Comment by claudep** [comment]
I know some prefer `pytest` over `unittest`, but I'd like to know the advantages in this particular lib. That's a real question, not a rant of some sort!

**Comment by deeplook** [comment]
`Pytest` uses no boilerplate code, is more flexible and more _Pythonic_. It reports differences between received and expected structured results on deeper levels. It is easier to use when testing for raised or upraised exceptions (if I remember correctly). And it's a project that sees continuous improvements unlike anything in the `unittest` world. And there are surely more reasons I don't remember now.

**Comment by claudep** [comment]
Thanks for developing your arguments. I think I'll still need to see real examples to be convinced, but anyway, it's not a blocker for my contributions at all.

**Comment by deeplook** [comment]
Will start by a simple restructuring.
