### ISSUE TITLE
Why is output PDF b/w for a colored svg input?

### ISSUE THREAD

**Issue by JorjMcKie** [deeplook/svglib#105]
Here is the example svg input and pdf output (created with svglib):
[silicon2018.zip](https://github.com/deeplook/svglib/files/1628852/silicon2018.zip)

**Comment by claudep** [comment]
Because the color is defined in a CSS rule in that file, and svglib doesn't support CSS yet.

**Comment by claudep** [comment]
With this file (CSS fill property moved to element directly), this should work.
[silicon2018.zip](https://github.com/deeplook/svglib/files/1629619/silicon2018.zip)

**Comment by JorjMcKie** [comment]
Thank you very much indeed. That helped a lot!
