### ISSUE TITLE
Generated PDF is all black

### ISSUE THREAD

**Issue by jsvachon2** [deeplook/svglib#111]
Hi,

I am using pygal to generate a SVG file which displays just fine in my browser. But when I convert it to any other format (PDF, jpg, png) using svglib, all I am getting is a picture completely black.

I am on OSX, do I need any additional package/library installed?

Thanks

**Comment by claudep** [comment]
You may imagine that without the SVG file, we cannot say much about this :-)

**Comment by jsvachon2** [comment]
Yeah I guess this would help. The tool does not support svg so I renamed it to a text file

[cpuusage.txt](https://github.com/deeplook/svglib/files/1793929/cpuusage.txt)

**Comment by jsvachon2** [comment]
Not sure if this will help but using the svg2pdf binary is also generating a black  image...

/tmp $ svg2pdf cpuusage.svg

[cpuusage.pdf](https://github.com/deeplook/svglib/files/1794780/cpuusage.pdf)

**Comment by deeplook** [comment]
@jsvachon2 Not sure, I've heard of http://pygal.org/en/stable before. Your example seems to be created with v. 2.4.0. Do you observe that effect for all your samples created with pygal or only some, or only this one? :)

**Comment by claudep** [comment]
The reason is that style is defined by a stylesheet in your SVG document, and svglib doesn't support that yet (just opened #112 to track that issue).

**Comment by claudep** [comment]
@jsvachon2 Could you please also attach the expected output as image?
