### ISSUE TITLE
Coloured markers get filled with black upon rendering as PDF

### ISSUE THREAD

**Issue by lmortimer** [deeplook/svglib#119]
I've got a simple matplotlib graph with one red and one green marker. Saving the figure as svg it renders correctly (attached graph.svg). When I draw the same graph on a reportlab Canvas and save it the markers are now filled with black (attached document.pdf).

Any idea on what is causing this behaviour? This is on Python 2.7, Ubuntu 14.04 running with the latest versions of reportlab and svglib . Script and requirements.txt to reproduce are attached.
 
Thanks

Attachments are in the zip below
[svgbug.zip](https://github.com/deeplook/svglib/files/1831784/svgbug.zip)

**Comment by claudep** [comment]
Thanks for the report, I tracked the bug to the `style` attribute of `<use>` nodes not taken into account.
You might try the following patch:
```
diff --git a/svglib/svglib.py b/svglib/svglib.py
index 94dc293..c82e0ae 100755
--- a/svglib/svglib.py
+++ b/svglib/svglib.py
@@ -561,6 +561,7 @@ class SvgRenderer:
             # Append a copy of the referenced node as the <use> child (if not already done)
             node.append(copy.deepcopy(self.definitions[xlink_href[1:]]))
         self.renderNode(node.getchildren()[-1], parent=group)
+        self.shape_converter.applyStyleOnShape(group, node)
         getAttr = node.getAttribute
         transform = getAttr("transform")
         x, y = map(getAttr, ("x", "y"))
```

**Comment by claudep** [comment]
My initial diagnostic was not the good one, the issue was more perverse! Finding attributes from parents was short-circuited when the node had a `style` attribute.

**Comment by lmortimer** [comment]
Thanks for fixing this. Could you give me an estimate of when you will publish a new release on pypi?

**Comment by claudep** [comment]
@deeplook is the releaser.

**Comment by deeplook** [comment]
I am looking actively for some tool to help producing releases more quickly, because the frequently I do it the more I forget about the entire process/procedure... Any suggestions are highly appreciated. I've found here and there some helpers used by some projects, but maybe I need to combine some of that.

**Comment by claudep** [comment]
Documenting the release process (for example in the Wiki, https://github.com/deeplook/svglib/wiki) could be a first step, because then people might suggest improvements/tools to improve the process.

**Comment by deeplook** [comment]
Good idea. I rushed away and created this initial page: https://github.com/deeplook/svglib/wiki/Release-Process
