### ISSUE TITLE
When using viewBox attribute, canvas size is not scaled to width and height of svg attribute

### ISSUE THREAD

**Issue by matthiastns** [deeplook/svglib#121]
When trying to convert the following svg to png

```
from svglib.svglib import svg2rlg
from reportlab.graphics import renderPDF, renderPM

svgtemplate="""
<svg   width="1250" height="1250"  viewBox="-40 -40 80 80">
<rect width="30" height="30" style="fill:red" />
</svg>
"""
def png(svg,pngfilename):
    text_file = open("template.svg", "w")
    text_file.write(svg)
    text_file.close()
    drawing = svg2rlg("template.svg")
    renderPM.drawToFile(drawing, pngfilename)

png(svgtemplate,'Test_viewBox.png')
```

I receive a png that is only 80px x 80px.
It should be 1250 x 1250 and the rect should be scaled accordingly.

(svglib 0.8.1 python 3.6.4 Windows 7)

**Comment by Overdrivr** [comment]
@tomturner  Anything I can do to help getting this merged ? I recently switched a project from cairoSVG to svglib, and it's the only thing that's still preventing me from completing the transfer.

**Comment by claudep** [comment]
@Overdrivr just for my own curiosity, why are you switching back from cairoSVG?

**Comment by Overdrivr** [comment]
Because of the dependency on cairo. I'm fed up with dependencies that are a total mess to install and maintain. Also, now with pipenv enforcing good practices for dependency management, software that rely on hacks to install 3rd party dependencies are doomed to disappear.

**Comment by Overdrivr** [comment]
BTW in case someone else cannot wait for this patch as well, I have merged this patch with latest master in my own repository, it's available here: https://github.com/cronobo/svglib/tree/i121-viewbox-img-dims
All credits to @tomturner 

```
pip install git+https://github.com/cronobo/svglib@i121-viewbox-img-dims#egg=svglib
```

I have not checked if it passes CI, I cannot guarantee it's working ok. But it passes extensive unit testing of my own application, so that's a good sign this patch is on the right track

**Comment by tomturner** [comment]
@Overdrivr I need to do some test before I submit the patch again. Hopefully @claudep or @deeplook will then approve it as I need it too. @Overdrivr Have you got a test SVG i can use?

**Comment by claudep** [comment]
I may not have fixed all concerns in PR #134, but your opinions and tests are welcome there.

**Comment by tomturner** [comment]
@claudep did you see my new code?

**Comment by claudep** [comment]
Tom, could you make a new PR then?

**Comment by claudep** [comment]
@tomturner can you confirm you're working on a new PR?

**Comment by Overdrivr** [comment]
Hi folks, any updates on this ? Otherwise I can open a PR from my repo. I'll add the necessary tests, but otherwise, according to my own application test's suite and extensive use, the modifications on my repo are definitely healthy.

**Comment by claudep** [comment]
My local tests show that at least the use case provided in the initial description is solved now. I'm closing the ticket, feel free to reopen (possibly a new ticket) if you find unresolved cases.
