### ISSUE TITLE
Draw to numpy array

### ISSUE THREAD

**Issue by Overdrivr** [deeplook/svglib#128]
Is there a way to draw SVG to memory, such as numpy array, instead of files ?

The only workaround I see for now is to draw to a temporary file, and load it afterward, but that's not great

**Comment by claudep** [comment]
Please precise your question as we do not draw SVG, we read SVG and draw to PDF or other Reportlab-supported output formats.

This is more a ReportLab question than a svglib question, but we could add in our README that `drawToFile` accepts any file-like Python objects, or that one can use the (misnamed) `drawToString` API to get the content as a binary buffer.

**Comment by claudep** [comment]
Can this question be considered answered with commit  d97e237 ?

**Comment by claudep** [comment]
I hesitated about mentioning `drawToString`. However, I generally think it's better practice to create the file object and pass it to `drawToFile`, because then you know exactly what type of file object you have in your hands.
