### ISSUE TITLE
Issue with nested svg tags, producing incorrect image.

### ISSUE THREAD

**Issue by charles-wright** [deeplook/svglib#139]
using svglib-1.8.1, Python 3.6.2 :: Anaconda custom (32-bit)
installed using pip

I am working with svg files where I need to used nested svg tag to establish local coordinate reference frames.  The library does not produce the appropriate output with nested tags.  I reduced the examples to a very minimal level.

_Unfortunately the issue editor does not support attaching SVG or python files so I will include below._

File 1:  Nested SVG Example
`<?xml version="1.0" encoding="utf-8" ?>
<svg height="520" version="1.1" width="600">
    <defs>
    <svg height="30" width="300" x="0" y="0">
        <defs />
        <text x="0" y="15" fill="black">Test text</text>
    </svg>
</svg>`
Blank image file:  
![file 1](https://user-images.githubusercontent.com/38887387/39877685-915e9fde-5444-11e8-8dd0-4423988ae845.png)
End of image

File 2: Non Nest Example:
`<?xml version="1.0" encoding="utf-8" ?>
<svg height="30" width="300" x="0" y="0">
    <defs />
    <text x="0" y="15" fill="black">Test text</text>
</svg>`
Image with text:
![file 2](https://user-images.githubusercontent.com/38887387/39877695-96a7bc28-5444-11e8-8daa-b33eae783dc7.png)

The python code is pretty much straight from documention:

`"""Convert svg to png"""
from svglib.svglib import svg2rlg
from reportlab.graphics import renderPM, renderPDF

drawing = svg2rlg("file.svg")
renderPM.drawToFile(drawing, "file.png", fmt="PNG")
`
Is there something I need to do either within my code or the svg file to get this to work?

**Comment by claudep** [comment]
We've added some embedded SVG support in https://github.com/deeplook/svglib/commit/ed72ad538fa8a597031ecbf03e1352a06595346b (only in master, unreleased). It would be great if you could test your use case with the master branch.

**Comment by charles-wright** [comment]
I originally started with a conda install, but uninstalled it, then did a simple pip install which got me the 0.8.1 version.  I will uninstall that as well and try the repo version.

**Comment by deeplook** [comment]
Thanks for mentioning conda! We also need to find a way to create releases for conda automatically, somehow. More in https://github.com/deeplook/svglib/issues/140.

**Comment by charles-wright** [comment]
I uninstalled via pip again, and made sure report lab as removed as well.  I used your pip command and it installed via git, and included report lab as well.  No change in output.

**Comment by deeplook** [comment]
@charles-wright Sorry for the late reply, please have a look at `TestSVGEmbedded` in `/test/test_basic.py` which declares an XML namespace for the `svg` element. Could you retest after setting such a namespace?

**Comment by claudep** [comment]
Depends on what you call "internal" style. An example snippet would be nice.

**Comment by charles-wright** [comment]
Here is a simple example:

```
<?xml

 version="1.0"?>
<svg 
    xmlns="http://www.w3.org/2000/svg" version="1.1" height="520" version="1.1" width="600">
    <defs>
        <style type="text/css">
            <![CDATA[
.minLabelText {
    font-family: Arial, Helvetica, sans-serif;
    font-size: 14pt;
    fill: black !important;
}

.refLabelText {
    font-family: Arial, Helvetica, sans-serif;
    font-size: 12pt;
    text-anchor: middle;
    fill: black !important;
}

.maxLabelText {
    font-family: Arial, Helvetica, sans-serif;
    font-size: 12pt;
    text-anchor: end;
    fill: black !important;
}]]>
        </style>
    </defs>
    <g>
        <svg 
            xmlns="http://www.w3.org/2000/svg" version="1.1" height="30" width="300" x="0" y="0">
            <text class="minLabelText" x="0" y="15" fill="black">
                <tspan>Lower</tspan>
                <tspan x="0" y="28">Performance</tspan>
            </text>
            <text class="refLabelText" x="2.0in" y="15">
                <tspan>Borderline</tspan>
                <tspan x="2.0in" y="30">Performance</tspan>
            </text>
            <text class="maxLabelText" x="4in" y="15">
                <tspan>Higher</tspan>
                <tspan x="4in" y="30">Performance</tspan>
            </text>
        </svg>
    </g>
</svg>
```

**Comment by claudep** [comment]
Thanks, that is indeed unsupported in current released versions. I merged partial support for style sheets in master yesterday.

**Comment by charles-wright** [comment]
Thanks.  Closing this issue.

**Comment by charles-wright** [comment]
Just a follow up.  Nesting works if the child svg(s) are in a group.  Without the group there are still issues.
