### ISSUE TITLE
Percentage width not working properly on rect.

### ISSUE THREAD

**Issue by charles-wright** [deeplook/svglib#141]
Trying to create a background bar at the top of the svg area and put text on top of it.

```
<?xml version="1.0"?>
<svg 
    xmlns="http://www.w3.org/2000/svg" version="1.1" height="50" width="500">
    <rect height="0.25in" width="100%" x="0" y="0" fill="gray"/>
    <text x="3.5in" y="14">Performance Profile</text>
</svg>
```

Resultant image:
![file 1](https://user-images.githubusercontent.com/38887387/40016566-b4d70724-5784-11e8-9c07-7f60be77d3c9.png)

The gray bar should extend across the width of the svg tag.

**Comment by claudep** [comment]
That's true. The `percentOf` parameter of `Svg2RlgAttributeConverter.convertLength` is never provided in the current code. Might not be trivial to fix.

**Comment by claudep** [comment]
I just checked and can confirm that #186 is fixing this issue.
