### ISSUE TITLE
two version 0.8.1 tags

### ISSUE THREAD

**Issue by MinchinWeb** [deeplook/svglib#147]
it seems there are two tags for version 0.8.1

- https://github.com/deeplook/svglib/tree/v0.8.1/
- https://github.com/deeplook/svglib/tree/v.0.8.1/

One should probably be removed...

**Comment by MinchinWeb** [comment]
For what it's worth, they at least point to the same commit...

**Comment by deeplook** [comment]
Thanks! I've just deleted the v.0.8.1 sibling of v0.8.1.
