### ISSUE TITLE
Cannot convert 

### ISSUE THREAD

**Issue by Maverick-R** [deeplook/svglib#148]
I have a svg file that generated by pygal, it can't be successfully converted to png file, I got a total black picture。[](url)

**Comment by claudep** [comment]
Could you test with the master code, too?

**Comment by deeplook** [comment]
@Maverick-R, that's really not a lot of actionable information.

**Comment by claudep** [comment]
Feel free to reopen the ticket if you can reproduce the problem with the master branch.
