### ISSUE TITLE
Get feedback about moving to GitLab

### ISSUE THREAD

**Issue by deeplook** [deeplook/svglib#161]
I'm experimenting with a new project on GitLab, and if successful, might think about moving this project there, maybe in 2019. GitLab provides many additional features over GitHub, including integrated CI (supporting Unix, Windows, macOS). The community is surely smaller than GitHub's, but constantly growing and attracting ever more projects to move from GitHub especially since it was taken over by Microsoft. It also received $100M of D series investment money very recently. Any opinions?

**Comment by claudep** [comment]
I'm fine with moving the code on GitLab. I did it for some of my projects and the switch was a matter of minutes!

**Comment by Overdrivr** [comment]
I use extensively Gitlab for work projects, and overall I'm very happy with it.

However, for open-source projects, I am not sure a Gitlab project has the same visibility as a Github one (in terms of SEO), and personally, I also prefer how Github displays things like README, issues, etc.

Also, there are still some technical issues to resolve with Gitlab from time to time. Currently, per week, I have a couple of unavailability errors, like impossible to push, or 503s on Gitlab repo pages. It's overall getting better with time but still, it's not as fluid as Github in that matter. Page slowing is still pretty slow. But impact on work remains very limited.

Their CI is very good, but also has area to improve. The one feature that is particularly good is the ability to define multiple & different isolated jobs, that can run sequentially and/or parallel (mix and match like you want), which you can't do with Appveyor/Travis. Also, you can by simply installing a tool on a VM, add that VM to the runners. That means you can boot any VM, install `gitlab-ci-runner`, and immediately you can run gitlab CI jobs on that VM. Pretty dope.

On the other hand, the built-in CI runners sometimes fail with networking errors, docker errors and stuff like that. Recurrence is about a few times per week if you make an intensive use of the CI (in my case approximately 6000 minutes of CI/month).

> [...] including integrated CI (supporting Unix, Windows, macOS)

The `gitlab-ci-runner` can run on both three OSes, although please note that by default you can only run jobs run in Docker environment and therefore it's a Linux-only build. If you don't want to manage a VM, you will still have to rely on Appveyor for Windows builds. For Mac, I don't think there is any other way that using the `gitlab-ci-runner` on a Mac machine.

**Comment by deeplook** [comment]
@Overdrivr Thanks for the info! I also use GitLab at work, although not as much as I would like. With gitlab.com I'm surprised to see what is hopefully not a general performance issue but rather one related to my free plan, e.g. 13 seconds response times for very simple API calls like `GET https://gitlab.com/api/v4/snippets`...

**Comment by deeplook** [comment]
Deferring any real move to some unspecified point in the future...
