### ISSUE TITLE
AttrConverterTestCase failure on Python 2

### ISSUE THREAD

**Issue by claudep** [deeplook/svglib#17]
On Python 2, io.StringIO needs a unicode string. @deeplook, do you want to support Python 3.2? We could add the `u""` prefix before the string, but Python 3.2 doesn't support it (it was readded in 3.3).

**Comment by deeplook** [comment]
@claudep I don't think anybody _really_ cares about Python 3.2. I would start to care only at 3.4, when `pip` and `asyncio` became part of the proverbial _included batteries_, see https://docs.python.org/3/whatsnew/3.4.html.

**Comment by claudep** [comment]
That's my opinion, too. Thanks.
May I ask you to push the fix by prefixing the string passed to `io.StringIO` in `test_no_fill_on_shape`?

**Comment by deeplook** [comment]
There's no PR left including this. Or do I misunderstand something?

**Comment by claudep** [comment]
No, I was just lazy to create a PR for one character :-)

**Comment by deeplook** [comment]
Done.

**Comment by claudep** [comment]
Thanks!
