### ISSUE TITLE
Reopen Issue - Issues Between svglib 0.8.1 and 0.9.0

### ISSUE THREAD

**Issue by louis-gallo-cigna** [deeplook/svglib#172]
Hi Deeplook, 

My sincere apologies for not following back up with some issues with svglib creating poor quality monochrome issues when I upgrade to 0.9.0. 

I think I may see what is going on, and it is probably my fault. 

If I use 0.9.0 under Linux, I get error messages when the process runs.

Unable to find a suitable font for 'font-family:Nimbus Sans L'

If I downgrade back to 0.8.1, everything is fine, no errors, and my charts look great.

Any ideas what I am doing wrong or missing.

Any help greatly appreciated.

Lou

**Comment by claudep** [comment]
I think any report without a real example has about 0 chances to be solved, sorry. Please reopen when you can upload one.
