### ISSUE TITLE
passing file-like object to svg2rlg

### ISSUE THREAD

**Issue by Akuli** [deeplook/svglib#173]
I want to use `svg2rlg` with `io.BytesIO`, but it wants a path to a file, and not a file-like object, so I need to create a `tempfile.NamedTemporaryFile`, copy the `BytesIO` content there, and then `svg2rlg` with that temporary file's name. This is a bit inconvenient, and can be slow with large files. Ideally `svg2rlg` could also take a file-like object instead of a path.

Currently `svg2rlg` has `svgz` code that creates an `svg` file in the same directory as where the `svgz` file is. That must be changed to implement this because `BytesIO` objects don't even have a directory where they are, but I think that using a temporary file or `BytesIO` would be better anyway.

**Comment by claudep** [comment]
There is support for file-like objects, the test suite is using `StringIO` extensively as input. It might chokes on `BytesIO` as it expects text input. What's the error you get?

**Comment by Akuli** [comment]
I didn't even try it because `svg2rlg` does `os.remove(path)` at the end. There's no way that could possibly work with file objects.

**Comment by Akuli** [comment]
I read the code a bit more carefully. The `os.remove(path)` is for `svgz` files only anyway, but the `path` is passed to `SvgRenderer`. Then it passes it to `Svg2RlgShapeConverter`, which inherits its `__init__` from `SvgShapeConverter` that sets it to `self.svg_source_file`. The `Svg2RlgShapeConverter` then has code like `os.path.join(os.path.dirname(self.svg_source_file), xlink_href)` which would break if `svg_source_file` was a file object.

I'm feeling like if I pass a file object to `svg2rlg`, it might "work", until I try to use some feature that just doesn't happen to work with file objects (or my code gets an SVG file that has some stuff that svglib handles differently).

**Comment by Akuli** [comment]
Reading the code even more: the `os.path.dirname(self.svg_source_file)` code runs only if the SVG contains images that are not embedded in it as base64, so I think it'll be fine for my needs. Might be nice to document this though. Sorry for the wall of text!

Which encoding should I use if I have an SVG file's content as bytes, and I want to create a `StringIO`-like file object from it? `utf-8`?

**Comment by deeplook** [comment]
If you got up to here, you might want to contribute a patch I guess it would be well accepted.

On the encoding, I'd always start with UTF-8.

**Comment by claudep** [comment]
Thanks for the explorations. I just added a fix/test in #174 to prevent a nasty crash in a case you mention.

**Comment by Akuli** [comment]
I have used svglib with a file object for a while and it works
