### ISSUE TITLE
External svg image does not work

### ISSUE THREAD

**Issue by metro69** [deeplook/svglib#175]
I am trying to convert a simple svg that references another svg (see below).

Using svglib 0.9.0, reportlab 3.5.13.

test.svg is correctly rendered by Chrome.
svg2pdf returns with:
`Unable to read the image another.svg#rectangle. Skipping...`

Metro

test.svg:

`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"    width="1000" height="1000">
    <image xlink:href="another.svg#rectangle" class="blue"/>
</svg>
`

another.svg
`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"    width="1000" height="1000">
    <rect x="558.5" y="570" width="75" height="50" id="rectangle" />
</svg>`

**Comment by claudep** [comment]
You are right, this is not supported yet. First, support for external svg should be added, then targeting a specific element in an linked svg should be implemented (probably a bit harder).

**Comment by claudep** [comment]
The pull request above is implementing the first stage of the fix only.

**Comment by metro69** [comment]
Thanks. I can now include svg's into another svg by removing the '#rectangle' and render to pdf using svg2pdf.

However, the transform does not seem to work yet. For instance, the svg below puts both rectangles at the same location.

I assume that is part of the next phase fix. Is there something I can do in the interim?

Metro

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"    width="1000" height="1000">
<g>
    <image xlink:href="another.svg" class="blue"/>
    <image transform="translate(200,200)" xlink:href="another.svg" class="blue"/>
    </g>
</svg>
```

**Comment by claudep** [comment]
#179 should improve the situation, we are not far from being able to target an external fragment. Could you test it on your use case?

**Comment by metro69** [comment]
The last update seems like a step back. I uninstalled svglib and reinstalled directly from your repo:
`pip install git+https://github.com/claudep/svglib@xlink_href
`
None of the two rectangles show up anymore in the generated pdf.

Metro

**Comment by claudep** [comment]
Thanks for trying, I will explore that in the next days.

**Comment by claudep** [comment]
I added a new commit to #179 which might solve your issue.

**Comment by metro69** [comment]
Transform is now working.

However, the rendered result seems to ignore attributes like fill and stroke in the included svg. For instance, if I add "fill="#ff0000" to rect in another.svg, the rendered PDF shows two black rectangles instead of red.

MT
--

**Comment by metro69** [comment]
I tested with your latest commit in `claudep:ext_fragment` and my test cases are now working.

Thanks!
Metro

**Comment by claudep** [comment]
Many thanks for your feedback!
