### ISSUE TITLE
Decide on continued Windows support

### ISSUE THREAD

**Issue by deeplook** [deeplook/svglib#197]
At the moment we have AppVeyor fails for every merge. I don't see anybody except @nicoddemus who would care for this and be able to solve it. If I'm right maybe it's worth doing something about it, and keep some records of how to do it? Otherwise I feel we should drop official Windows support with the next release. Opinions?

The last error from AppVeyor was this: https://ci.appveyor.com/project/deeplook/svglib/builds/25657065

**Comment by nicoddemus** [comment]
I wasn't aware that the AppVeyor builds were failing, sorry.

I'm happy to fix it and keep it running in the future, as we develop multi-platform applications (including Windows) which use `svglib`. I will take a look later.

If AppVeyor fails without obvious reasons, feel free to ping me.
