### ISSUE TITLE
SVG colors no supported?

### ISSUE THREAD

**Issue by mrgou** [deeplook/svglib#203]
It seems that svglib does not support SVG colors, or at least note the svg2rlg method.

For instance, when processing an SVG file generated by GraphViz:
```
In [1]: from svglib.svglib import svg2rlg
In [2]: drawing = svg2rlg('dot_graph.svg')
Can't handle color: transparent
Can't handle color: slategrey
```
I'm looking forward for a release that support SVG color keywords (https://www.w3.org/TR/2013/WD-SVG2-20130409/single-page.html#types-ColorKeywords).

**Comment by mrgou** [comment]
Does this update cover the full range of SVG color keywords?

**Comment by claudep** [comment]
I think so, the code will use that list in ReportLab: https://bitbucket.org/rptlab/reportlab/src/afaf3fc6a8d847bb70b79306dfff16998e23ada5/src/reportlab/lib/colors.py#lines-532

**Comment by mrgou** [comment]
Oh yes, that looks complete! Looking forward to its release in PyPi! :-)
