### ISSUE TITLE
Can't handle color: var(--cape-base)

### ISSUE THREAD

**Issue by milkyklim** [deeplook/svglib#208]
I am trying to load svg image that contains 

```
* {
  ...
  --cape-base: #FFFFFF;
  ...
}
```

color declaration. 

I can't figure out why error `Can't handle color: var(--cape-base)` is thrown.

Here is the [image](https://milkyklim.keybase.pub/issues/3425.svg).

Code I'm using:

```
from svglib.svglib import svg2rlg
drawing = svg2rlg('3425.svg')
```

Is this issue related https://github.com/deeplook/svglib/issues/203?

**Comment by claudep** [comment]
This is not related to #203. The fact is that the [cssselect2](https://github.com/Kozea/cssselect2) lib used by svglib is not resolving the `var()` constructs, neither are we.

**Comment by milkyklim** [comment]
Closing this one here then.
