### ISSUE TITLE
Dropping Python 2

### ISSUE THREAD

**Issue by claudep** [deeplook/svglib#216]
As Python 2 is about to reach its end of life, I think it's about time we drop support in svglib.
@deeplook, what's your take on this?

**Comment by deeplook** [comment]
I'm much in favor of dropping Python 2.x support with its "end of life" coming by the end of 2019. I would suggest we then stop testing it in Travis and state we don't support 2.x anymore in the docs with a release 1.0 to come in 2020. From then on we can also apply simplifications, clean-ups, whatever that can happily break it on Python 2.7. Sounds like a plan? 😊

**Comment by claudep** [comment]
Good plan. I could make a 0.9.3 release rather soon stating that it is the last release supporting Python 2, what do you think? Or would you prefer waiting for the end of the year?

**Comment by deeplook** [comment]
Even better (of course)! 😊
