### ISSUE TITLE
Support Python 3.8 in Travis?

### ISSUE THREAD

**Issue by deeplook** [deeplook/svglib#221]
After dropping Python 2.7 we might want to support 3.8. ;) I've looked at the Travis site, but I haven't seen a non-dev 3.8 version, yet.

**Comment by claudep** [comment]
It should be doable (see https://github.com/jazzband/tablib/blob/master/.travis.yml and https://travis-ci.org/jazzband/tablib)

**Comment by deeplook** [comment]
Or does this indicate full 3.8 support? https://docs.travis-ci.com/user/languages/python/

**Comment by claudep** [comment]
I'm sure it does.

**Comment by deeplook** [comment]
Tablib looks nice, thanks for the hint! I also like https://github.com/jazzband/tablib/blob/master/RELEASING.md which I feel like copy-pasting into this repo... It might have caused more releases over the last years... ;)

**Comment by claudep** [comment]
Fixed by b0f5d863953dbd116042582da499ea48e04101f1
