### ISSUE TITLE
Graph's data plotted out of limits

### ISSUE THREAD

**Issue by GabiWenzel** [deeplook/svglib#225]
Dear all,

Thank you for this package. When trying to convert my with python created .svg files to a .pdf file, the data is plotted also outside the axes, meaning outside the limits I set (compare figure2.svg to figure3.pdf). How can I get rid of this?

Please find a working example below. Thank you for any input and/or help with this issue!
All the best,
Gabi

[figures.zip](https://github.com/deeplook/svglib/files/4140769/figures.zip)

`import numpy as np
import matplotlib.pyplot as plt
import svgutils.compose as sc
from IPython.display import SVG
from pylab import rcParams
rcParams['figure.figsize'] = 4 , 3

# some 'data'
x = np.linspace(0,10,100)
y1 = np.exp(x)
y2 = 2*np.exp(x)**2

# the figure
fig0 = plt.figure(0)
fig0.subplots_adjust(left=0.15, bottom=0.15, right=0.95, top=0.95)
ax = fig0.add_subplot(111)
ax.grid(True, lw = 0.5, ls = '--', c = '.5') # adds a grid
ax.set_xlabel(r'xlabel')
ax.set_ylabel(r'ylabel')
ax.ticklabel_format(style='sci', axis ='y', scilimits=(0,0) , useMathText=True) # x and y axis format
ax.set_yscale('log')  # plot y axis as a log scale
ax.set_ylim(0,10000)
ax.plot(x, y1, label='Mode 1')
ax.plot(x, y2, label='Mode 2')
ax.legend(loc='upper right')
plt.show()

# save the figure as svg
fig0.savefig('figure1.svg', transparent=True, bbox_inches='tight')

# assemble figure with any other svg file
sc.Figure("286.578", "221.355",
    sc.Panel(sc.SVG("figure1.svg")),
    sc.Panel(sc.SVG("2-methynaphthalene.svg").scale(0.5).move(40,70))
    ).save("figure2.svg")
SVG('figure2.svg')

# now convert to pdf
from svglib.svglib import svg2rlg
from reportlab.graphics import renderPDF

drawing = svg2rlg("figure2.svg")
renderPDF.drawToFile(drawing, "figure3.pdf")`

**Comment by claudep** [comment]
The problem is that the `<defs>` where the clipping path of several element of the SVG file is defined is at the end of the file, so svglib doesn't find it as it processes nodes sequentially. It's probably a limitation of svglib. It could process all defs section first, and then all other nodes.

**Comment by claudep** [comment]
PR #231 should solve this issue. Anyone wanting to test it is welcome!

**Comment by nzny01** [comment]
Thanks for the fix. I tried branch svglib-issue225 and it fixes the problem.

Before:

![image](https://user-images.githubusercontent.com/61595917/75597552-109a5280-5a64-11ea-9275-967cdede6362.png)

After

![image](https://user-images.githubusercontent.com/61595917/75597602-60791980-5a64-11ea-857b-ad449d3984fb.png)

**Comment by claudep** [comment]
Many thanks for testing and confirmation! I'll merge the PR soon.
