### ISSUE TITLE
reportLab svg2rlg bug when handling clip-paths

### ISSUE THREAD

**Issue by nzny01** [deeplook/svglib#230]
It appears that clip-paths are ignored when importing SVG files into reportLab PDF with svg2rlg.

If an SVG file has a graphics object with a clip-path assigned (this is typical for matplotlib graphics where the plot extends outside an axis), then the SVG file will not render properly when importing into a reportLab PDF via svg2rlg.

The SVG file looks correct in AI or Explorer, so the problem appears to be with svg2rlg.

The problems appears to be that svglib parses the SVG XML tree assuming that clip-paths will be present in the tree before they are used, which is not the case for matplotlib SVG exports (clip-paths are at the bottom of the XML tree).

The easiest way I found around this (seems to be working) is just to run the renderNode loop twice in renderSvg: the first time on a throw away group, the second time with the actual group instance.

The first pass will build the Group instance self.definitions dict, which will then be fully populated and available the second pass.

```
def renderSvg(self, node, outermost=False):
    _saved_preserve_space = self.shape_converter.preserve_space
    self.shape_converter.preserve_space = node.getAttribute("{%s}space" % XML_NS) == 'preserve'

    group_throwaway = Group()
    for child in node.getchildren():
        self.renderNode(child, group_throwaway)

    group = Group()
    for child in node.getchildren():
        self.renderNode(child, group)
```

**Comment by claudep** [comment]
Thanks for the report and the suggestion. A similar issue was reported in #225.
