### ISSUE TITLE
throwing ValueError for SVG 1.2 tiny files

### ISSUE THREAD

**Issue by k0mplex** [deeplook/svglib#232]
Hello, 

I've got a question. When I call svg2rlg for a svg 1.2 file (the full tag is \<svg width="595.44" height="841.68" xmlns="http://www.w3.org/2000/svg" xmlns:_xmlns="xmlns" _xmlns:xlink="http://www.w3.org/1999/xlink" version="1.2" baseProfile="tiny" style="background-color:#fff"\>) I yield the following exception: 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\path\to\svglib.py", line 1422, in svg2rlg
    drawing = svgRenderer.render(svg_root)
  File "C:\path\to\svglib.py", line 580, in render
    main_group = self.renderSvg(node, outermost=True)
  File "C:\path\to\svglib.py", line 834, in renderSvg
    self.renderNode(child, group)
  File "C:\path\to\svglib.py", line 643, in renderNode
    item = self.shape_converter.convertShape(name, n, clipping)
  File "C:\path\to\svglib.py", line 945, in convertShape
    shape = getattr(self, method_name)(node)
  File "C:\path\to\svglib.py", line 1257, in convertPath
    rx, ry, phi, fA, fS, x2, y2 = nums
ValueError: not enough values to unpack (expected 7, got 3)

Apparently the elliptical arc in this older version contains only 3 numbers. Catching this exception in the module, I found, that there are also elliptical arcs with different amount of numbers given (starting from 1 to 6, but never 7). Is there any support or workaround for such 'broken' files? Many thanks in advance!

**Comment by claudep** [comment]
Would be nice if you could provide us with the complete svg file. And also a pointer to a reference to any spec defining this simplified elliptical arc, if possible.

**Comment by k0mplex** [comment]
Hello claudep,

Thank you very much for your reply. I've attached an [example](https://github.com/deeplook/svglib/files/4270640/example.txt) of a music sheet, which contains such elliptic arcs. 

Some detailed descriptions on the svg 1.2 tiny specification can be found [here](https://www.w3.org/TR/SVGMobile12/paths.html#PathData). I hope, that this can help you. 

Again many many thanks in advance!

**Comment by claudep** [comment]
Unfortunately, there isn't any mention of elliptic arcs in the svg 1.2 tiny spec.
However my feeling right now by reading your file is that the issue could come from interpretation of the double zeros in a sequence like `a1.533 1.533 0 00-.648-1.266`.

**Comment by claudep** [comment]
OK, now I'm sure this is related to the flags parameters to arc (`large-arc-flag` and `sweep-flag`) which are `1`/`0` values which don't require spaces around. Our `utils.split_floats` function needs a fix.

**Comment by claudep** [comment]
The failing test:
```
diff --git a/tests/test_basic.py b/tests/test_basic.py
index 2fc6912..3e41992 100755
--- a/tests/test_basic.py
+++ b/tests/test_basic.py
@@ -83,6 +83,9 @@ class TestPaths:
             ("M10 20, l 5e-5,0",
                 ["M", [10, 20], "l", [5e-5, 0]]),
 
+            ("a1.518 1.518 0 011.195-.547",
+                ["a", [1.518, 1.518, 0, 0, 1, 1.195, -0.547]]),
+
             ("m246.026 120.178c-.558-.295-1.186-.768-1.395-1.054-.314-.438-.132-.456 1.163-.104 "
              "2.318.629 3.814.383 5.298-.873l1.308-1.103 1.54.784c.848.428 1.748.725 "
              "2.008.656.667-.176 2.05-1.95 2.005-2.564-.054-.759.587-.568.896.264.615 1.631-.281 "
```

**Comment by k0mplex** [comment]
Thank you very much for your quick reply and help! I can verify that the latest update fixed my issue.
