### ISSUE TITLE
Svglib is breaking Gunicorn

### ISSUE THREAD

**Issue by igormcsouza** [deeplook/svglib#243]
I'm using svglib on a backend environment, along side with Flask. After installing it, I got an error on gunicorn.

```
usage: gunicorn [-h] [-f FOLDER] [-it INPUT_TYPE]
gunicorn: error: unrecognized arguments: -b 0.0.0.0:2002 --access-logfile - --reload app:app
```
That is not happening when svglib is not installed. I'm using python 3, there is also Keras and Tensorflow installed on the environment. I'm using docker to build environment. My Gunicorn version is 19.9.0

**Comment by claudep** [comment]
I'm sorry for you, but with so few information, it's impossible for us to debug the issue, or even tell if svglib is really the culprit. Feel free to reopen if you can give more details on the error.

**Comment by igormcsouza** [comment]
Well.. I'm not sure what more is needed to debug it! Just create an environment with svglib, gunicorn==19.9.0 and flask. Create a simple application and run with gunicorn. The error will come up!

**Comment by claudep** [comment]
With the simple error line you reported above, it's simply impossible to find out what's the problem.
