### ISSUE TITLE
Enable GitHub discussions? 

### ISSUE THREAD

**Issue by deeplook** [deeplook/svglib#263]
How about enabling the GitHub discussions feature which could be useful e.g. for things that need to be opened as issues like https://github.com/deeplook/svglib/issues/262.

**Comment by claudep** [comment]
For me, discussions on tickets is sufficient for my needs, but if you want to try something else, why not.

**Comment by deeplook** [comment]
I've enabled discussions. Will add some text to the issue templates later, too...
