### ISSUE TITLE
Cache some external files downloaded during test runs

### ISSUE THREAD

**Issue by claudep** [deeplook/svglib#273]
To avoid connectivity issues during running CI tests and save some bandwidth, it should be great if we could cache access to the SVG test suite and the Wikipedia flags. https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows has some tips for that.

@eumiro, do you think that would be feasible?

**Comment by deeplook** [comment]
Would make a lot of sense.

**Comment by eumiro** [comment]
Sounds like a good idea, I can have a look at that later. Did you try anything?

**Comment by claudep** [comment]
No, I trust experts :-)
