### ISSUE TITLE
when I transform svg to png, it will draw some black block on pngs randomly, how does it happen?

### ISSUE THREAD

**Issue by Pean-Mura** [deeplook/svglib#287]

**Comment by deeplook** [comment]
Please share some code.

**Comment by Pean-Mura** [comment]
> Please share some code.

![0bfb4e39-ef17-4a6b-8c0a-fcd2cfb698ec](https://user-images.githubusercontent.com/70005731/120761469-cac21900-c547-11eb-827d-c45a8ceaea36.png)
above is the png I got .below is the origin svg
![image](https://user-images.githubusercontent.com/70005731/120762092-7c614a00-c548-11eb-9c24-9e7e309ee696.png)

                        drawing = svg2rlg(file)
                        renderPM.drawToFile(drawing,out+name+'.png',fmt='PNG')
code just like this, nothing special. but i process 16 imgs continusly. It randomly get the black block on 2 or 3 imgs.

**Comment by deeplook** [comment]
Please share a complete minimal example.

**Comment by Pean-Mura** [comment]
> Please share a complete minimal example.


[m.zip](https://github.com/deeplook/svglib/files/6597153/m.zip)
This is the svg file. you can download and try it.  and then is my whole code
import tqdm
import os
import datetime
import time
from svglib.svglib import svg2rlg
from reportlab.graphics import renderPM
import traceback


def imgs_generator(path,slice_size):#分批处理图片
    imgNames = []
    def walkPath(path):
        for root,dirs,files in os.walk(path):
            for f in files:
                imgNames.append(os.path.join(root,f))
    walkPath(path)
    if len(imgNames) %  slice_size != 0:
        n_slice = len(imgNames) // slice_size + 1
    else:
        n_slice = len(imgNames) // slice_size
    for n in range(n_slice):
        start,end = n*slice_size,(n+1)*slice_size
        yield imgNames[start:end]
        
def get_command(path,out,slice_size,Del):
    batch_sample = imgs_generator(path,slice_size)
    batch_label = True
    n_num = 1
    try:
        while batch_label:
            singleBatch = batch_sample.__next__()
            print('processing_batch_{}\n'.format(n_num))
            time.sleep(0.5)
            for file in tqdm.tqdm(singleBatch):
                try:
                    suffix = file.split('.')[1]
                    name = os.path.split(file)[1][:-4]
                    if suffix == 'svg':
                        drawing = svg2rlg(file)
                        renderPM.drawToFile(drawing,out+name+'.png',fmt='PNG')
                        if Del:
                            os.unlink(file)
                except Exception as e:
                    print(e)
            n_num += 1
    except Exception as e:
        if type(e) == StopIteration:
            batch_label = False
        else:
            traceback.print_exc()


if __name__ == '__main__':
    Total_start = time.time()
    slice_size = 10000
    files = [r'C:\Users\Administrator\Desktop\m'
             ]
    
    outs = [r'C:\Users\Administrator\Desktop\SVG\\'
            ]
    for i in range(len(files)):
        file_path = files[i]
        out_path = outs[i]
        start = time.time()
        get_command(file_path,out_path,slice_size,Del=False)
        #Del is the on-off to delete SVG
        end = time.time()
        t = start - end
        print('Time:%d s' % t)
    Total_end = time.time()
    print('Total_time:',datetime.timedelta(seconds=Total_end-Total_start))


Maybe you will run several times to get the problem.

**Comment by Pean-Mura** [comment]
> Please share a complete minimal example.

[m.zip](https://github.com/deeplook/svglib/files/6597173/m.zip)


This is the SVG file. you can download and try it maybe.

and then is my code:
`import tqdm
import os
import datetime
import time
from svglib.svglib import svg2rlg
from reportlab.graphics import renderPM
import traceback


def imgs_generator(path,slice_size):
    imgNames = []
    def walkPath(path):
        for root,dirs,files in os.walk(path):
            for f in files:
                imgNames.append(os.path.join(root,f))
    walkPath(path)
    if len(imgNames) %  slice_size != 0:
        n_slice = len(imgNames) // slice_size + 1
    else:
        n_slice = len(imgNames) // slice_size
    for n in range(n_slice):
        start,end = n*slice_size,(n+1)*slice_size
        yield imgNames[start:end]
        
def process(path,out,slice_size):
    batch_sample = imgs_generator(path,slice_size)
    batch_label = True
    n_num = 1
    try:
        while batch_label:
            singleBatch = batch_sample.__next__()
            print('processing_batch_{}\n'.format(n_num))
            time.sleep(0.5)
            for file in tqdm.tqdm(singleBatch):
                try:
                    suffix = file.split('.')[1]
                    name = os.path.split(file)[1][:-4]
                    if suffix == 'svg':
                        drawing = svg2rlg(file)
                        renderPM.drawToFile(drawing,out+name+'.png',fmt='PNG')
                except Exception as e:
                    print(e)
            n_num += 1
    except Exception as e:
        if type(e) == StopIteration:
            batch_label = False
        else:
            traceback.print_exc()


if __name__ == '__main__':
    Total_start = time.time()
    slice_size = 100
    files = [r'C:\Users\Administrator\Desktop\m'
             ]
    
    outs = [r'C:\Users\Administrator\Desktop\SVG\\'
            ]
    for i in range(len(files)):
        file_path = files[i]
        out_path = outs[i]
        start = time.time()
        process(file_path,out_path,slice_size)
        end = time.time()
        t = start - end
        print('Time:%d s' % t)
    Total_end = time.time()
    print('Total_time:',datetime.timedelta(seconds=Total_end-Total_start))` 

maybe you will need to try several times to get the problem.

**Comment by Pean-Mura** [comment]
> Please share a complete minimal example.

[m.zip](https://github.com/deeplook/svglib/files/6597203/m.zip)
this is the SVG file. you can download and try it.
and my whole code is as flowing:
"import tqdm
import os
import datetime
import time
from svglib.svglib import svg2rlg
from reportlab.graphics import renderPM
import traceback


def imgs_generator(path,slice_size):
    imgNames = []
    def walkPath(path):
        for root,dirs,files in os.walk(path):
            for f in files:
                imgNames.append(os.path.join(root,f))
    walkPath(path)
    if len(imgNames) %  slice_size != 0:
        n_slice = len(imgNames) // slice_size + 1
    else:
        n_slice = len(imgNames) // slice_size
    for n in range(n_slice):
        start,end = n*slice_size,(n+1)*slice_size
        yield imgNames[start:end]
        
def process(path,out,slice_size):
    batch_sample = imgs_generator(path,slice_size)
    batch_label = True
    n_num = 1
    try:
        while batch_label:
            singleBatch = batch_sample.__next__()
            print('processing_batch_{}\n'.format(n_num))
            time.sleep(0.5)
            for file in tqdm.tqdm(singleBatch):
                try:
                    suffix = file.split('.')[1]
                    name = os.path.split(file)[1][:-4]
                    if suffix == 'svg':
                        drawing = svg2rlg(file)
                        renderPM.drawToFile(drawing,out+name+'.png',fmt='PNG')
                except Exception as e:
                    print(e)
            n_num += 1
    except Exception as e:
        if type(e) == StopIteration:
            batch_label = False
        else:
            traceback.print_exc()


if __name__ == '__main__':
    Total_start = time.time()
    slice_size = 100
    files = [r'C:\Users\Administrator\Desktop\m'
             ]
    
    outs = [r'C:\Users\Administrator\Desktop\SVG\\'
            ]
    for i in range(len(files)):
        file_path = files[i]
        out_path = outs[i]
        start = time.time()
        process(file_path,out_path,slice_size)
        end = time.time()
        t = start - end
        print('Time:%d s' % t)
    Total_end = time.time()
    print('Total_time:',datetime.timedelta(seconds=Total_end-Total_start))"

maybe you will try several times to get the problem

**Comment by deeplook** [comment]
Sorry, but I'm scared of ZIPs. ;) Would you mind putting the SVG on a gist for your GitHub account? (I've just updated the issue template accordingly.)

**Comment by Pean-Mura** [comment]
> Sorry, but I'm scared of ZIPs. ;) Would you mind putting the SVG on a gist for your GitHub account? (I've just updated the issue template accordingly.)

https://gist.github.com/Pean-Mura

okay, I have did that.

**Comment by Pean-Mura** [comment]
> Sorry, but I'm scared of ZIPs. ;) Would you mind putting the SVG on a gist for your GitHub account? (I've just updated the issue template accordingly.)

okay, I have done.
https://gist.github.com/Pean-Mura/9c04ad0c48ad831684da55eca40a8a81

**Comment by deeplook** [comment]
I've had a look at your SVG files using the following snippet to generate PNGs for all:

```python
from glob import glob
from svglib.svglib import svg2rlg
from reportlab.graphics import renderPM

for fn in glob('*.svg'):
    drawing = svg2rlg(fn)
    out = fn.split('.')[0] + '.png'
    renderPM.drawToFile(drawing, out, fmt='PNG')
```

I can see artifacts near some letters like B in 1.svg and 2.svg, but they don't look like black squares to me. See attached images. The Chinese (?) letters seem to be ignored in the PNG output, and appear with outlined squares in PDF output. This is likely a font issue.

For the artifacts you describe around some letters... I suggest you minimize some SVG example even more to only one letter causing this effect in order to isolate it more.

![1](https://user-images.githubusercontent.com/1001778/120884136-65226b00-c5e1-11eb-98a4-b19881f7e531.png)
![2](https://user-images.githubusercontent.com/1001778/120884137-65bb0180-c5e1-11eb-828f-e2f8e4a7a3e3.png)

**Comment by Pean-Mura** [comment]
> I've had a look at your SVG files using the following snippet to generate PNGs for all:
> 
> ```python
> from glob import glob
> from svglib.svglib import svg2rlg
> from reportlab.graphics import renderPM
> 
> for fn in glob('*.svg'):
>     drawing = svg2rlg(fn)
>     out = fn.split('.')[0] + '.png'
>     renderPM.drawToFile(drawing, out, fmt='PNG')
> ```
> 
> I can see artifacts near some letters like B in 1.svg and 2.svg, but they don't look like black squares to me. See attached images. The Chinese (?) letters seem to be ignored in the PNG output, and appear with outlined squares in PDF output. This is likely a font issue.
> 
> For the artifacts you describe around some letters... I suggest you minimize some SVG example even more to only one letter causing this effect in order to isolate it more.
> 
> ![1](https://user-images.githubusercontent.com/1001778/120884136-65226b00-c5e1-11eb-98a4-b19881f7e531.png)
> ![2](https://user-images.githubusercontent.com/1001778/120884137-65bb0180-c5e1-11eb-828f-e2f8e4a7a3e3.png)

Yeah, it's true that chinese characters will be ignored too. Is there anymethod to solve this problem?

**Comment by deeplook** [comment]
You can try using a dedicated font and/or find some clues in https://github.com/deeplook/svglib/issues/89.
