### ISSUE TITLE
Incorrect rendering of masked images

### ISSUE THREAD

**Issue by arkbene** [deeplook/svglib#290]
[minimal-bug.svg.zip](https://github.com/deeplook/svglib/files/7003898/minimal-bug.svg.zip)

produces:

[minimal-bug.pdf](https://github.com/deeplook/svglib/files/7003899/minimal-bug.pdf)

**Comment by claudep** [comment]
Yes, this is documented in the README under Known limitation: `clipping is limited to single paths, no mask support`.

If you have an idea to implement masks with Reportlab machinery, feel free to share your ideas.
