### ISSUE TITLE
svg convert to pdf with gray images

### ISSUE THREAD

**Issue by hbh112233abc** [deeplook/svglib#291]
**svg image**
[temp1629451352.8199928.svg.zip](https://github.com/deeplook/svglib/files/7029013/temp1629451352.8199928.svg.zip)
**convert to pdf**
[temp1629451352.8199928.pdf](https://github.com/deeplook/svglib/files/7029007/temp1629451352.8199928.pdf)

**env:**
win10 64bit
python 3.7 64bit
svglib 1.0.1

**demo:**
```
from svglib.svglib import svg2rlg
from reportlab.graphics import renderPDF

svg_file = 'temp1629451352.8199928.svg'
pdf_file = 'temp1629451352.8199928.pdf'

drawing = svg2rlg(svg_file)
renderPDF.drawToFile(drawing, pdf_file)
```

**error display**
![微信截图_20210823115413](https://user-images.githubusercontent.com/7788164/130387869-f03396b3-7bb3-449c-ad5a-f0ac0a2f014d.png)

And I use `cairosvg` convert pdf not found this problem!

**Comment by deeplook** [comment]
You don't provide much information except for the files. But I assume you don't expect the upper left black labels to be where they are, and I guess they are a copy of the lower right red ones. Can you strip down the SVG to a minimal size that shows this effect, please?

**Comment by hbh112233abc** [comment]
> Opening it in Firefox gives
> 
> ![bildo](https://user-images.githubusercontent.com/39555268/131016258-86fda076-bf8b-4386-a024-2ff410a2bcec.png)
> 
> So I think that's the expected output

the problem is the output pdf file has error! the svg image not found error!

**Comment by deeplook** [comment]
@hbh112233abc You can help debugging by minimizing your SVG to a version that shows the undesired effect.

**Comment by claudep** [comment]
I tried with most recent svglib version and the output looks a lot nicer now.
