### ISSUE TITLE
Convert rst to markdown

### ISSUE THREAD

**Issue by victorbnl** [deeplook/svglib#300]
I'd like to make a pull request to convert READMEs and other documents like NOTES from rst to markdown, as it's simpler, more used, more understood... Meaning people could understand it more easily when reading it directly and contribute more easily. Are you interested?

**Comment by deeplook** [comment]
The "simpler" usually refers only to markup for hyperlinks (simpler in Markdown, indeed), and in the only three ReST files we have we don't seem to use any advanced markup options, so the added value would seem questionable to me. Many well-known packages are using ReST or even a mix of ReST and MD, like https://github.com/scikit-learn/scikit-learn. ReST is without doubt the more expressive format, and would likely be used for some documentation for this package, too, using Sphinx. I know you can use Sphinx with MD, but you loose many of the possibilities provided by Sphinx plugins which work on ReST only. Altogether I don't think it's worth it.

**Comment by claudep** [comment]
If the added value is not plainly evident, I agree with @deeplook.
