### ISSUE TITLE
stroke-opacity not supported?

### ISSUE THREAD

**Issue by cbeytas** [deeplook/svglib#303]
Seems that stroke-opacity is not supported? It always defaults to "1"

```python
import lxml
from lxml.html import open_in_browser
import reportlab.graphics.renderPM
from svglib import svglib
SVG = """
<svg width="100" height="100">
    <circle cx="50" cy="50" r="40" fill="green" stroke="black" stroke-width="5"/>
    <path stroke="red" d="M10 50 90 50" stroke-opacity="0.5" stroke-width="10"/>
</svg>"""
parser = lxml.etree.XMLParser(recover=True, resolve_entities=False)
svg_root = lxml.etree.fromstring(SVG, parser=parser)
open_in_browser(svg_root)
renderer = svglib.SvgRenderer('test')
drawing = renderer.render(svg_root)
pil_image = reportlab.graphics.renderPM.drawToPIL(drawing)
pil_image.show()
```
![chrome](https://user-images.githubusercontent.com/4748055/135297669-918d4d79-d136-4875-9bcd-9a5ca1b5166f.png) Chrome
![svglib](https://user-images.githubusercontent.com/4748055/135297677-081d9518-1e02-49c3-9316-75609101d66a.png) svglib

**Comment by deeplook** [comment]
I see there is a test for it which indicates it is preserved: https://github.com/deeplook/svglib/blob/64c49440dc57104768e2c9e7d8337c68c010e1c8/tests/test_basic.py#L446

Have you tried that?

**Comment by cbeytas** [comment]
It does render mostly ok to a PDF file.
This seems to indicate a problem with the reportlab renderPM instead. I'll close this bug.

![pdf](https://user-images.githubusercontent.com/4748055/135325028-f92d63b4-29c3-4935-8fb9-565318a7f70d.png)
![pdfclose](https://user-images.githubusercontent.com/4748055/135325280-a50c3373-3f0c-468a-9d6f-7370bbe8b100.png)
