### ISSUE TITLE
Delete branch py2and3

### ISSUE THREAD

**Issue by deeplook** [deeplook/svglib#31]
@claudep Unless you find anything interesting in it, mostly here: https://github.com/deeplook/svglib/commit/f23ba4067ddbb5b18327b3d273980374539131cd

**Comment by claudep** [comment]
Well, it doesn't hurt to keep it a bit longer, but I don't think I'll take more ideas from it (maybe make the `xrange` -> `range` simplification).

**Comment by claudep** [comment]
@deeplook I think the branch can be safely removed now (unless you want to keep it for historical reasons).

**Comment by deeplook** [comment]
Done.
