### ISSUE TITLE
Axis details and legend are not shown for EPS but they appear in the PDF for the same svg.

### ISSUE THREAD

**Issue by ahmad88me** [deeplook/svglib#348]
Converting the SVG to the EPS loses the legend and the numbers on the axis. But that does not happen when converting the same SVG to PDF.

SVG: 
![t2dv2_mer_exact_reo_ca_nc-rec](https://user-images.githubusercontent.com/6922709/170950808-c2fd5676-b658-4eae-b832-b9774d37a1ad.svg)

Screenshot: (left is the PDF version and the right one is the EPS version)
![Screenshot 2022-05-30 at 10 26 54 AM](https://user-images.githubusercontent.com/6922709/170950882-7caad273-db28-4a9f-87aa-259187e4bf0c.png)

**Comment by claudep** [comment]
I'm afraid this may be a ReportLab issue (as the PDF looks OK). @replabrobin, any idea about what could explain such a difference?

**Comment by replabrobin** [comment]
It looks like a font issue. I cannot debug without the right svg, but when I view it in chrome I just see a black rectangle. I assume it must be right so I I will attempt the conversions.

**Comment by replabrobin** [comment]
OK the original svg has a problem somewhere. I tested various output formats including png, pdf, eps, py only pdf showed the text. If I generate svg using eg --outdir=../ --formats=svg then 1) the generated svg can be seen properly in chrome and 2) most of the outputs converted from it show the text. Interestingly eps still doesn't. 

This example has too many bits to debug properly. Everythiing in it is just curves so it can't be a font issue, but it might be opacity/colour handling etc etc.

**Comment by ahmad88me** [comment]
This SVG is generated using pandas (and seaborn). I have several different SVG files generated in the same way all having the same issue.  (just in case this info helps).

**Comment by claudep** [comment]
I'm afraid that svglib is not able to impact the issue with EPS rendering, sorry.
