### ISSUE TITLE
Installation Failed v 1.3.0 & 1.2.1

### ISSUE THREAD

**Issue by skrskr** [deeplook/svglib#349]
When i tried to install svglib version 1.3.0 and v 1.2.1
```
pip install svglib==1.3.0
pip install svglib==1.2.1
```
i get errors

```
ERROR: Could not find a version that satisfies the requirement svglib==1.3.0 (from versions: 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.8.0, 0.8.1, 0.9.0b0, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 1.0.0, 1.0.1, 1.1.0)
ERROR: No matching distribution found for svglib==1.3.0
```

```
ERROR: Could not find a version that satisfies the requirement svglib==1.2.1 (from versions: 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.8.0, 0.8.1, 0.9.0b0, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 1.0.0, 1.0.1, 1.1.0)
ERROR: No matching distribution found for svglib==1.2.1
```

**Comment by claudep** [comment]
Those release do exist, see https://pypi.org/project/svglib/#history

**Comment by skrskr** [comment]
yep, i now that but it's not working with me.

![svglib-error](https://user-images.githubusercontent.com/15523129/174552534-566f2f59-4b82-4db0-a3a9-c1f83cdfc528.jpeg)

**Comment by claudep** [comment]
I'm sorry for you, but I don't see what we can do for that on our side. You may try to upgrade your pip install.

**Comment by skrskr** [comment]
yep, it's required python version>=3.7 but my python version on server is 3.6 
thanks alt
