### ISSUE TITLE
pdb set_trace in 1.4

### ISSUE THREAD

**Issue by marksweb** [deeplook/svglib#352]
I can't see it in the project source here, but in my test suite, and confirmed in the tar ball from pypi, there is a `pdb.set_trace()` in this package, v1.4. Specifically there is `import pdb; pdb.set_trace()` on line 1339, in `applyStyleOnShape`

You can see the output of my test suite showing this;
https://github.com/marksweb/django-filer/runs/7694659281?check_suite_focus=true

**Comment by claudep** [comment]
Doh!! Sorry for the bad release and many thanks Mark for reporting it! I'll release 1.4.1 asap.

**Comment by marksweb** [comment]
@claudep if that came about because you'd been debugging something locally and that's where you built & released, I can thoroughly recommend releasing via github actions.

It's something I've brought to many packages and works on a simple workflow that requires a secret for pypi in the repo and gets triggered when you publish a release on here.

Here's an example; https://github.com/django-cms/django-filer/blob/master/.github/workflows/publish-to-live-pypi.yml

I also use a similar thing to publish to test.pypi.org when PRs merge to ensure that the main branch is releasable.

**Comment by claudep** [comment]
Thanks for the tip, I know the trend is to use GitHub actions. I generally prefer doing thing by hand, but I know the downside is errors like this one.
