### ISSUE TITLE
SVG not imported in PDF

### ISSUE THREAD

**Issue by TheeAntoine** [deeplook/svglib#356]
Hi everyone, I have an issue when I try to import an SVG image on my PDF, I used the following code :

`drawing = svg2rlg("Logo_CE.svg")`
`renderPDF.draw(drawing, canvas, 23.5*mm,13.6*mm)`

When I open my PDF file, nothing appears : 
![Screenshot_27](https://user-images.githubusercontent.com/48049654/185054828-4da7c813-a02f-4204-96ed-bfd9bf39c041.png)

This is my expected result : 
![Screenshot_28](https://user-images.githubusercontent.com/48049654/185054917-1f0bceb8-02da-431c-846b-8c297da1011e.png)

When I import a PNG file it works but I want to do the same with SVG.
Someone know how to solve this ?

**Comment by claudep** [comment]
The first thing to check is to only convert your SVG logo to PDF, to check if the rendering of the SVG file hasn't any issue.

**Comment by claudep** [comment]
Closing, waiting for an answer to my remark above.
