### ISSUE TITLE
convert to pdf and png files is incorrect

### ISSUE THREAD

**Issue by alan0526** [deeplook/svglib#360]
svglib==**1.4.1** installed via pip.
Python **3.9.2**

I use svglib and reportlab to convert svg to pdf and png

**Files**
**SVG** ![bmw logo](https://user-images.githubusercontent.com/35990424/201469839-97d370e7-b399-4389-8878-82f8f02f8f53.svg)
**PDF** [bmw logo.pdf](https://github.com/deeplook/svglib/files/9994750/bmw.logo.pdf)
**PNG** ![bmw logo](https://user-images.githubusercontent.com/35990424/201469885-55af0cd6-7ca3-4021-830d-3134b2e0aa48.png)

**Code**
from svglib.svglib import svg2rlg
from reportlab.graphics import renderPDF, renderPM

def svg2pdf(svg_path, path):
    drawing = svg2rlg(svg_path)
    renderPDF.drawToFile(drawing, path)

def svg2fmt(svg_path, path, fmt="PNG", dpi=75):
    drawing = svg2rlg(svg_path)
    renderPM.drawToFile(drawing, path, fmt=fmt, dpi=dpi)

the converted pdf and png is not correct, both of them are look different.

**Comment by claudep** [comment]
The PNG renderer is known to be limited, see also #299.

Could you tell us what make you think the PDF is not correct?
By the way, the method used to draw the logo is not optimal (circle with big stroke and dasharray), SVG has arcs that would be more appropriate and probably more precise.

**Comment by alan0526** [comment]
I want to create a rotated bmw logo with svg, convert it to pdf, and send it to our chart supplier. it is used for camera quality test, so the accuracy is very import.
But after I convert this svg to pdf, the pattern looks different.
Thanks for you advice, I will try to use arcs to draw this pattern.

**Comment by alan0526** [comment]
here are files base on svg arcs(path)
PNG: ![chart](https://user-images.githubusercontent.com/35990424/201563677-bca2b802-8d52-4a17-9e09-233626ec531b.png)
SVG: ![chart](https://user-images.githubusercontent.com/35990424/201563679-f498b67a-a0f7-46ce-b11e-ad85c34ad19d.svg)
PDF: [chart.pdf](https://github.com/deeplook/svglib/files/9999069/chart.pdf)

svg and pdf seems correct, but the png arcs are not very smooth, is there any setting for png generator?

**Comment by claudep** [comment]
You may try the alternate PNG renderer as in https://github.com/deeplook/svglib/issues/299#issuecomment-918111040. Anyway, there is nothing svglib can do to fix that, therefore closing.
