### ISSUE TITLE
Extend svg2pdf to generate other formats

### ISSUE THREAD

**Issue by deeplook** [deeplook/svglib#37]
This should be easy given that there are other ReportLab renderers, like `renderPM` for bitmaps and `renderPS` for Postscript. And with `renderSVG` one could also do round-trip testing. The most difficult question then might be which name to choose for this extended tool instead of `svg2pdf`?

**Comment by claudep** [comment]
Maybe keep the names in sync with RL and have several `svg2pdf`, `svg2pm`, etc. scripts? Of course, with much code reuse between scripts.

**Comment by deeplook** [comment]
Yes, this would likely work for most without breaking expectations. One could even include a script named `svg2svg` for thrills. ;-) I was just scared of using names like `svg2any` or so. And stuff like _ImageMagick_ uses `convert` which is _way_ to general.

Maybe in that sense even `svg2*` is too general and there should be a tool/script named after the package. But then, that works best for proper names like _ImageMagick_ (maybe abbreviated to something), and less so for generic name like `svglib`.

**Comment by deeplook** [comment]
The preliminary `pdf2ps` and `pdf2pm` scripts are still buggy due to some import buglet on Py 2 after the restructuring.

**Comment by deeplook** [comment]
Will delay this for a future release and remove the existing initial code to increase test coverage.
