### ISSUE TITLE
Reportlab 4.0.0 added dependency to pycairo

### ISSUE THREAD

**Issue by danielrivard** [deeplook/svglib#376]
It appears that the latest version of reportlab ([released May 4th](https://pypi.org/project/reportlab/4.0.0/)) has added a dependency to pycairo, requiring lib cairo to be installed on the system.

This was my main point to use svglib in the first place, to not need that dependency.

I was able to workaround it by adding the last 3.X version to my requirements file.
reportlab==3.6.13

Otherwise, I get errors of pip trying to build the pycairo wheel and not finding the packages on my system.

**Comment by claudep** [comment]
That was the right move, that is pinning the reportlab dep on your side. Duplicate of #375.

**Comment by danielrivard** [comment]
Sorry I had missed there was another issue for this.

Thanks.
