### ISSUE TITLE
Release a Python 3 compatible version on PyPI

### ISSUE THREAD

**Issue by claudep** [deeplook/svglib#44]
I think it would be nice to make a release on PyPI with the recent improvements of svglib. Is that in your plans?

**Comment by deeplook** [comment]
Definitely! I'm aiming for a release 0.7.0 before 2017! To get there it might help me to re-focus on applying some remaining face lift details in setup.py and the test suite and stash work on `svg2pdf` siblings...

**Comment by claudep** [comment]
Sure, good plan!

**Comment by deeplook** [comment]
Well, time is running out for 2016. Is there anything blocking a release, or making it mandatory? I mean we can also do it over the next few days. Shall we have a todo list, declare a feature freeze or that kind of thing? Do we want to release despite issue #47? I would also like to include a tested `tox.ini` file which I'd prefer to run on something like an Amazon EC2 box, maybe with a little deployment script in this repo. I just have to collect code from other projects...

**Comment by claudep** [comment]
No rush... but on another side, nothing prevents re-releasing in a short time. A release would have the advantage to get some more testing.
Issue #47 is not a blocker, as it might well be an issue we can not resolve ourselves.
A CI server (travis-ci.org or anything else) would be nice, but I don't know if it's acceptable to download stuff from Wikipedia at each run...

**Comment by deeplook** [comment]
Ok, then I conclude we should rather I'm for a release in early January. Maybe you can comment on what you expect about CSS and gradients support in that context? Thanks!

**Comment by claudep** [comment]
I'm not sure to have time to work on new features in the short term, so feel free to release when you want. For me, it'll already be a great progress over 0.6.3.

**Comment by deeplook** [comment]
Sure! It's already much improved now over the old 0.6.3! I'll make s list of files with any kind of issues I find after looking at all output PDFs from the test suite.

**Comment by deeplook** [comment]
@claudep @replabrobin Is there any work on features left to be done before a new release of `svglib`? I'm thinking of skipping 0.7 and bump it to 0.8, reserving a little room for gradients which might then justify 1.0. We should also make very clear which `reportlab` version works best with any new `svglib` to be released. As far as I'm concerned it might happen the next weekend.

**Comment by claudep** [comment]
I would say that there are always new features that could be done. Let's have a release as soon as possible. Nothing prevents us of doing more releases as new features are committed.

**Comment by skidzo** [comment]
Hi!, If I can do **something** to help out, please let me know! I can test for the Python 3.5 on Mac, Win7, and Ubuntu, on Windows I am using an Environment, that I installed myself, but on mac and linux I use Anaconda 4.2.0 (64-bit). I am using reportlab currently in a project, and I have a few svg files, that i would like to use...

**Comment by deeplook** [comment]
@skidzo Sounds great! Any help is welcome! Testing is always a good thing (installing `pytest-xdist` accelerates that quite a bit). I'm mostly on Miniconda 2 and 3 on a Mac. @claudep is likely on Linux. @replabrobin will certainly have some Win version, but I assume that's also the most neglected platform (I certainly ignore it ;-). 

If you find any issues on your SVG files (apart from gradients), please consider providing a simplified version, if only temporarily. That's all that comes to my mind now.

**Comment by deeplook** [comment]
Done, hooray! https://pypi.python.org/pypi/svglib/0.8.0

**Comment by claudep** [comment]
\o/
