### ISSUE TITLE
Spread the news about the next release on StackOverflow

### ISSUE THREAD

**Issue by deeplook** [deeplook/svglib#51]
There are some threads about `svglib` there, see http://stackoverflow.com/search?q=svglib which could benefit from a brief update about the next release (after making the release).

**Comment by skidzo** [comment]
I have put a minimal example into one Question that sounded most clear to me:

http://stackoverflow.com/questions/16513940/embed-svg-files-into-pdf-using-reportlab

and I am not really satisfied about the work-flow here, maybe you have a suggestion:

    from svglib.svglib import svg2rlg
    drawing = svg2rlg(path)
    sx=sy=factor
    drawing.width,drawing.height = drawing.minWidth()*sx, drawing.height*sy
    drawing.scale(sx,sy)
    #if you want to see the box around the image
    drawing._showBoundary = True

this gives me a instance of reportlab.graphics.shapes.Drawing()

as you can see i had to use this extra modification of width and height values, to get scaling right.
I was using the drawingjust as like a reportlab.platypus.Flowable()

How can I write my own class SvgImage(Flowable), that provides a convenient to scale or wrap the image to a specified space?

**Comment by deeplook** [comment]
If you embed an SVG in a PDF, it should be not surprising you have to rescale the SVG using `drawing.scale()`. It has to be done *somewhere*. For now `svglib` contains no such `SvgImage`, but maybe it will in a future version. Feel free to open an issue for that! This one was rather intended, as the title says, to not forget to spread the news about the coming release.

**Comment by skidzo** [comment]
Ok, looking forward to that release!

a big THANKS by the way!

I will open the "Issue"
this seems to be a more reportlab related Issue anyway...

**Comment by claudep** [comment]
I think this issue is now a bit outdated.
