### ISSUE TITLE
Paths are closed which shouldn't be

### ISSUE THREAD

**Issue by deeplook** [deeplook/svglib#55]
I think there might be an issue with closing paths which also shows in a series of flag examples, e.g. that of Bhutan. I've condensed the following minimal example from `tests/samples/wikipedia/symbols/Flower-of-Life-small.svg`:

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
	xmlns:svg="http://www.w3.org/2000/svg"
	xmlns="http://www.w3.org/2000/svg"
	width="304"
	height="304"
	id="svg2"
	version="1.0">
	<g
		id="idLayerDrawing"
		style="display:inline"
		transform="translate(-348,-348)">
		<path
			style="opacity:1;fill:none;fill-opacity:1;fill-rule:nonzero;stroke:#000000;stroke-width:1;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-opacity:1;visibility:visible;display:inline;overflow:visible;enable-background:accumulate"
			id="path4481"
			d="M 543.30127,375 A 50,50 0 0 1 500,400"
			transform="translate(-43.30127,-25)"
			/>
	</g>
</svg>
```

Clearly, there is no `z` in the path here, but for some reason this seems to be ok. Maybe it's the `fill-rule:nonzero` style... (well, apparently not).

**Comment by claudep** [comment]
Yes, I'm working on it, too. My local patch is almost ready.
