### ISSUE TITLE
"y" in "tspan" interpreted as relative coordinate?

### ISSUE THREAD

**Issue by jdugge** [deeplook/svglib#81]
I tried to convert an SVG that contains the following text node, which contains a `y` key both in the `text` tag and in the `tspan` code:

```svg
  <text
     id="text125"
     data-bb="18"
     style="font-family: &quot;Open Sans&quot;, verdana, arial, sans-serif; font-size: 12px; fill: rgb(68, 68, 68); fill-opacity: 1; visibility: inherit; white-space: pre;"
     transform="translate(24.66,0)"
     y="234"  // y is defined here...
     x="0"
     text-anchor="middle">
    <tspan
       id="tspan121"
       y="234"  // ... and here again
       x="0"
       dy="0em"
       class="line">Oct 6</tspan>
    <tspan
       id="tspan123"
       y="234"
       x="0"
       dy="1.3em"
       class="line">2013</tspan>
  </text>
```

This node disappears off the page when converting it using `svg2pdf`, presumably because in https://github.com/deeplook/svglib/blob/master/svglib/svglib.py#L720, the y coordinates are added. If I understand correctly, the inner `y` keyword should be interpreted as an absolute coordinate though, so the outer `y` should be ignored in this case.

[plot.svg.txt](https://github.com/deeplook/svglib/files/907594/plot.svg.txt)

**Comment by claudep** [comment]
The result is still not perfect because em units are not implemented yet, but the y position should be correct with the patch.

**Comment by jdugge** [comment]
Thank you so much @claudep for the super fast help, and @deeplook for maintaining this project! Much appreciated!
