### ISSUE TITLE
Remaining little flag artefacts

### ISSUE THREAD

**Issue by deeplook** [deeplook/svglib#83]
Three flags in `samples/wikipedia/flags` show minor but clearly visible artefacts with paths and/or clipping: `Kyrgyzstan.svg`, `Slovenia.svg` and `The_republic_of_china.svg`.

**Comment by claudep** [comment]
After a quick look, these are probably different issues.
For `The_republic_of_china.svg`, it's probably an issue with `viewbox` vs svg height and width.
For `Slovenia.svg`, it's a svg inside another svg (currently unsupported).
For `Kyrgyzstan.svg`, it's probably an issue with `clipPath` being a circle (should check if Reportlab supports that or not).

**Comment by deeplook** [comment]
Likely correct...

**Comment by claudep** [comment]
Issue #124 should address the SVG embedding problem.

**Comment by claudep** [comment]
I think all previously reported artefacts are now gone.
