### ISSUE TITLE
font-weight is not handled

### ISSUE THREAD

**Issue by htgoebel** [deeplook/svglib#88]
`<text>` and `<tspan>` do not handle font-weight.

The following document renders the same text at almost the same position. The second one should be bold (with the "not" rendered normal). As you can see, both text have the same width.
``` xml
<?xml version="1.0" standalone="no"?>
<svg width="210mm" height="297mm"
     xmlns="http://www.w3.org/2000/svg" version="2">
<text x="5cm" y="10cm" xml:space="preserve"
      font-family="Verdana" font-size="32" fill="blue"><tspan/>
<tspan>Hello, out </tspan>
<tspan font-weight="bold" fill="red">not</tspan><tspan> there!</tspan>
<tspan x="5cm" dy="32">Zeile 2b iIlL</tspan>
<tspan font-family="serif" x="5cm" dy="32">Zeile 3 iIlL</tspan>
  </text>

<text x="5cm" y="10.1cm" xml:space="preserve"
      font-family="Verdana" font-size="32" font-weight="bold" ><tspan/>
<tspan>Hello, out </tspan>
<tspan font-weight="normal" fill="lightgreen">not</tspan><tspan> there!</tspan>
<tspan x="5cm" dy="32">Zeile 2b iIlL</tspan>
<tspan font-family="serif" x="5cm" dy="32">Zeile 3 iIlL</tspan>
  </text>
</svg>
```
![grafik](https://cloud.githubusercontent.com/assets/784161/26762187/1b34fb62-493e-11e7-807b-2a3f30541dfb.png)

**Comment by deeplook** [comment]
While this can be actually true, testing it with a font like Verdana makes little sense without embedding that font in the output PDF, which is not supported yet, IIRC, as mentioned in #89.

**Comment by 2minchul** [comment]
same problem. `font_weight='bold'` not working for me

**Comment by morphonedev** [comment]
Ragarding this issue I tested a little. (Platform Windows 10)
Created a test svg in Inkscape and got something like this : [FontSample.svg.txt](https://github.com/deeplook/svglib/files/5770408/FontSample.svg.txt)
(Had to rename it to txt to get it uploaded).
While the intended result is:
![IntendedResult](https://user-images.githubusercontent.com/51243253/103652721-ce834c80-4f63-11eb-8211-6a40af3446d0.png)
The result looks likes this:
![FontSample_Org](https://user-images.githubusercontent.com/51243253/103652790-e8249400-4f63-11eb-9875-fee01691cdc7.png)
Even after registering the necessary fonts:
```
register_font("Times New Roman", 'times.ttf')
register_font("Courier New", 'cour.ttf')
```
The result is:
![FontSample_Org-Reg](https://user-images.githubusercontent.com/51243253/103653013-33d73d80-4f64-11eb-98e4-817e2890bbc5.png)

So my proposal would be to introduce a font map were a font family, weight and style can be mapped to specific font.
Then something like:
```
register_font("Times New Roman", 'times.ttf')
register_font("Times New Roman", 'timesbd.ttf', weight='bold')
register_font("Times New Roman", 'timesi.ttf', style='italic')
register_font("Times New Roman", 'timesbi.ttf', weight='bold', style='italic')
```
would create the desired output.

If you are interested in such a solution, a can provide a pull request, with the necessary changes.

**Comment by deeplook** [comment]
All contributions are welcome! Just make sure to check if this is something to add to svglib or rather to reportlab itself, maybe.

**Comment by deeplook** [comment]
Can we close this now that we have https://github.com/deeplook/svglib/pull/268?

**Comment by claudep** [comment]
I just test the above font svg file, and all lines render fine except the `Times-Italic weight 800` one. But this could be handled in a new ticket, discussing how numeric font weight should be handled (e.g. > 700 could be converted to Bold).

**Comment by deeplook** [comment]
Fine, then let's close this, and feel free to open a new one.
