### ISSUE TITLE
Choose image dimensions when calling renderPM.drawToFile

### ISSUE THREAD

**Issue by astrike30** [deeplook/svglib#90]
Is there any way to choose the dimensions of the image that is saved by calling `renderPM.drawToFile` or by any other method?

**Comment by deeplook** [comment]
Using `svg2pdf` from the command-line I believe you cannot change the dimensions, but if you use it programmatically you can apply methods like `.scale()` on the `Drawing` instance that you get from `svg2rlg("file.svg")`...

**Comment by astrike30** [comment]
I am actually using python so that sounds like exactly what I need, can you point me at some docs for that `.scale()` method? :) Thanks

**Comment by deeplook** [comment]
[IPython](http://ipython.org) is your friend (the respective ReportLab docstring is pretty terse, though:)

```python
In [1]: from reportlab.graphics.shapes import Drawing

In [2]: Drawing.scale?<TAB>
Signature: Drawing.scale(self, sx, sy)
Docstring: Convenience to help you set transforms
File:      ~/miniconda3/lib/python3.5/site-packages/reportlab/graphics/shapes.py
Type:      function
```

**Comment by astrike30** [comment]
Thanks :)

**Comment by deeplook** [comment]
Sorry, but I fail to find a simple link on reportlab.com or https://bitbucket.org/rptlab/reportlab...

Maybe this can give you a nice example, instead: https://stackoverflow.com/questions/13345284/reportlabs-code128-barcode-as-html-image-tag-with-data-uri-scheme-in-python#13350788

**Comment by astrike30** [comment]
Thanks again :)

**Comment by jablka** [comment]
I'm having the same issue, but the `scale()` is not working for me...
What is wrong? My code here:
```python
from svglib.svglib import svg2rlg
from reportlab.graphics import renderPDF, renderPM
drawing = svg2rlg("my.svg")
drawing.scale(196,196)
renderPM.drawToFile(drawing, "output.png", fmt="PNG")
```
Thanks
