### ISSUE TITLE
Slow to install

### ISSUE THREAD

**Issue by kooky** [deeplook/svglib#91]
I installed svglib today with pip.

The install didn't finish before something timed out.

I disabled test cases, installs and works fine.     It wasn't use CPU - maybe a download hung or something.

I couldn't work out why, I'll have a look later.

**Comment by deeplook** [comment]
Running the test suite for the first time will take a significant amount of time, mostly because a lot of SVG sample files are downloaded from Wikipedia. Later it should be faster. A simple `pip install svglib` should not run the test suite, though.
