### ISSUE TITLE
Think about using this package to render GeoJSON files

### ISSUE THREAD

**Issue by deeplook** [deeplook/svglib#92]
Converting GeoJSON into something visual is still kind of an unnecessarily complicated issue. Using sites like geojson.io or GitHub gists makes this easier, but creating something quickly local seems to be overly complex, often  involving some node.js tools. It might be interesting to come up with a simple solution using `svglib` to convert them into SVG and from there to PDF. Any practical help would be highly welcome.

**Comment by claudep** [comment]
This is surely an interesting goal. However, I think this would be the task of a separate utility. IMHO svglib should focus on what it's designed for: read SVG and convert to other formats.
