### ISSUE TITLE
Embedded PNG images don't show up?

### ISSUE THREAD

**Issue by petri** [deeplook/svglib#93]
I get a "Adding box instead of image." warning for each embedded PNG image. The output PDF has no images. Any suggestions?

Here's the stanza for the embedded PNG images: 

`<image xlink:href="data:image/png;base64,iVBORw0KGgoAA.../>`

And the code:

```
from svglib.svglib import svg2rlg
from reportlab.graphics import renderPDF, renderPM

drawing = svg2rlg("input.svg")
renderPDF.drawToFile(drawing, "output.pdf")
```

**Comment by deeplook** [comment]
Thanks for your report! I don't have a lot of time nowadays to look into this. But I'd suggest you look into the test suite for something similar and/or create a similar case with a sample PNG, either a non-copyrighted one or one you create dynamically using https://pypi.python.org/pypi/pypng.

**Comment by deeplook** [comment]
Is this related to #94, maybe?

**Comment by claudep** [comment]
@petri it would be nice to have an example file at hand.

**Comment by jacobj** [comment]
+1 embedded png images don't seem to show up on both Python 3.5.4 and 3.6.2

**Comment by deeplook** [comment]
Can anybody please provide reproducible code? Thanks! I'll add something around these lines in a *submitting bug reports* section in the README, soon...

**Comment by petri** [comment]
The issue is easy enough to reproduce and there is no question about it being valid, imho. The fact that svglib warns "Adding box instead of image." regardless of what the image type is (PNG or other) suggests to me this is a known issue. Or if not, what does that warning mean if not that???

A proper test would have to check the internals of the resulting PDF to somehow detect whether the PNG is there. I don't have time to learn how to do that, just for a single test case that I have no certainty will result the issue getting fixed.

Having said that, here's a svg that can be used to confirm the issue (zipped because github does not support svg uploads): [png_in_svg.zip](https://github.com/deeplook/svglib/files/1358395/png_in_svg.zip)

I tried converting that and got the above-mentioned error.

**Comment by petri** [comment]
To check the PDF, I am pretty sure pdfrw can do the trick: https://pypi.python.org/pypi/pdfrw

**Comment by claudep** [comment]
Thanks for the sample file. I have a preliminary patch available here:
https://github.com/deeplook/svglib/compare/master...claudep:issue93
However, the image is reversed in the document. @deeplook I already struggled with shapes reversed in past patches, do you know what's wrong with coordinates?

**Comment by deeplook** [comment]
@claudep I've finally looked at your patch. Have run it only on the provided Wikipedia logo. Looks ok, but I confirm the image gets flipped vertically. The effect disappears when adding an `transform="translate(0, 841.89) scale(1, -1)"` attribute to the `image` element, where `841.89` is the height of the `svg.viewBox` attribute. I have to play more with it, though...

Also, the [SVG specs](https://www.w3.org/TR/SVG/struct.html#ImageElement) say, a renderer should implement at least PNG, JPEG and SVG as image formats, so SVG might be the funniest of this three left to support.

**Comment by claudep** [comment]
Thanks for investigating. Let's focus on bitmap formats with this ticket.
