### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by petri** [deeplook/svglib#94]
Running the tests, I see following failures on OSX, Python 3.6, on current svglib master:

tests/test_samples.py::TestWikipediaFlags::test_convert_pdf ERROR
(while processing tests/test_samples.py::TestWikipediaFlags::test_convert_pdf)

Later the following simply hangs forever:

tests/test_samples.py::TestW3CSVG::test_convert_pdf_png 
(while processing tests/samples/W3C_SVG_12_TinyTestSuite/svg/paint-stroke-207-t.svg)

**Comment by petri** [comment]
Looks like the Wikipedia flags are not downloaded for some reason...

**Comment by deeplook** [comment]
I've just run a freshly cloned version (on OSX, Python 3.5) from github without any issues at all. This includes the file you mention, which produces the PNG below. So I guess you must have some local issues, maybe network or whatever. Providing details of example runs is usually helpful.

![paint-stroke-207-t-svglib](https://user-images.githubusercontent.com/1001778/30929805-e5711f6a-a3bf-11e7-9aaf-11bc232b2e1b.png)

**Comment by petri** [comment]
I am running Python 3.6.2 in a virtualenv. Maybe that makes a difference.

What kind of details do you mean? What I provided above are copied from output of `py.test -s -v`

**Comment by deeplook** [comment]
I mean a snapshot of the terminal interaction including output. Here is what I did without output. Maybe you want to replicate it. I cannot promise to be super-responsive, though, concerning issues, I can't reproduce immediately.

```
cd ~/Downloads
git clone git@github.com:deeplook/svglib.git
cd svglib
PYTHONPATH=. py.test -v
```

**Comment by petri** [comment]
Got it. I had missed a new required post-install step when installing Python 3.6+ ... See http://www.cdotson.com/2017/01/sslerror-with-python-3-6-x-on-macos-sierra/ (also applicable on OSX El Capitan). Basically SSL certificate verification failed when fetching the test files.
