### ISSUE TITLE
Running svg2rlg second time returns None.

### ISSUE THREAD

**Issue by hovodab** [deeplook/svglib#95]
I have to draw an image on every page of a PDF file. For that I have a function that does something like this:
```
def draw_logo(file_path):
      rlg = svg2rlg(file_path)
      # Draw on PDF. This part doesn't matter...
```
And for every page I call the function draw_logo. It draws the image on the first page, but when the function is called second time(for second page) svg2rlg returns None. Yet I have found a way to bypass this case, I still think things shouldn't work so.

**Comment by claudep** [comment]
I cannot reproduce. Are you sure `file_path` is a real file path, or is it another file-like Python object?
Do you get a "Failed to load input file!" error log line the second time?

**Comment by hovodab** [comment]
@claudep It is a real file path(str). What is your version of svglib? I use 0.8.1.

**Comment by claudep** [comment]
Changes on master from the 0.8.1 release are minor, I don't think that makes a difference.
Are you able to place a breakpoint inside the `svg2rlg` function to see what's happening?
Is your file a `.svg` or `.svgz` file? Which Python? On Linux, Mac, Windows?

**Comment by hovodab** [comment]
File is `.svg`
Ubuntu==16.04, python==3.5.2

**Comment by claudep** [comment]
I have quite a similar configuration (Debian instead of Ubuntu). That's a weird behavior.
Is the following Python code running fine for you?:
```
from lxml import etree
etree.parse("/var/www/control/media/logos/logo.svg")
etree.parse("/var/www/control/media/logos/logo.svg")
```
I don't see how the document would be empty the second time.

**Comment by hovodab** [comment]
Yes, this runs without errors.

**Comment by claudep** [comment]
I'm sorry, I don't see any obvious error on svglib side which would explain this error. I'm afraid you'll have to debug a bit more on your side.

**Comment by hovodab** [comment]
@claudep Yes, I think I should. Thank you for your help. I will try to dig deeper.
