### ISSUE TITLE
Support *pathlike* objects.

### ISSUE THREAD

**Issue by MinchinWeb** [deeplook/svglib#97]
What am I proposing is that `svglib.svglib.svg2rlg()` accept a path-object created by `pathlib.Path()` (added to the standard library in Python 3.5) rather than just strings.

I have pathlib is a wonderful addition to my Python programming, and it would be a touch simpler if I could use it directly with svglib.

**Comment by deeplook** [comment]
I like the idea. I just have never used `pathlib` myself, yet. It should be a simple thing to contribute, which I'm encouraging you to do (while not giving up Python 2.7 compatibility).

**Comment by MinchinWeb** [comment]
Thanks @deeplook ; I'll look into it, but I can't give you a timeline at the moment!
