### ISSUE TITLE
Contact owners of stale forks of svglib

### ISSUE THREAD

**Issue by deeplook** [deeplook/svglib#98]
There seem to be some stale forks of `svglib` on GitHub which were made a long time ago and which don't reflect the many changes that were added with version 0.8.1. I'm getting some requests from people confused by those, and maybe this can be changed by contacting those who have made the forks... 

Here's a very preliminary list:

- https://github.com/DataMarket/svglib
- https://github.com/sweh/svglib

To be continued...

**Comment by deeplook** [comment]
*Message to forkers of this repository*

If you have an old fork of this package published on [pypi.org](https://pypi.org), please consider marking it as stale or even remove it from there as the latest version, 0.9.0, has been much improved over previous ones from some years ago, especially those before v. 0.8.0. This might help reduce some potential confusion for new users searching for a library like this. Thank you!

@144lab @amprosol @ategt @bayangan1991 @cclaus @chrisbennight @claudep @Acidburn0zzz @gabrielponto @cronobo @duke24k @gerrat @jdgwf @jdugge @joinerysoft @koodaamo @lordmauve @MinchinWeb @nicoddemus @replabrobin @ScanTrust @schneck @skidzo @tomturner @winglq @yhminnj

**Comment by claudep** [comment]
The published svglib variants on Pypi have been removed. About the Github forks, I guess that's a common situation where everyone is free to create its own fork and maintain/update it or not. I don't think we should make more efforts in this regard.
